# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('offer_id', models.CharField(max_length=16)),
                ('date_posted', models.DateField()),
                ('valid_through', models.DateField()),
                ('job_title', models.CharField(max_length=256)),
                ('job_location', models.CharField(max_length=512)),
                ('employer', models.CharField(max_length=256)),
                ('raw_html', models.TextField()),
                ('job_description', models.TextField()),
                ('job_benefits', models.TextField()),
                ('job_qualifications', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TagOfferRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.FloatField(default=1)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Offer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='tags',
            field=models.ManyToManyField(through='offers.TagOfferRelationship', to='offers.Tag'),
        ),
    ]
