# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date_posted',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_through',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
